# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=80)),
                ('project_link', models.URLField()),
            ],
        ),
    ]
